stages:
  - build
  - push
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  CHART_DIR: helm/trackad-task

image: docker:28
services:
  - docker:dind

build-image:
  stage: build
  script:
    - docker build --target runtime -t $IMAGE_TAG -f docker/app.prod.Dockerfile .
  only:
    - main

push-image:
  stage: push
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker push $IMAGE_TAG
  only:
    - main

deploy:
  stage: deploy
  image:
    name: alpine/helm:3.17
    entrypoint: [""]
  before_script:
    - echo "$KUBE_CONFIG" | base64 -d > /tmp/config
    - export KUBECONFIG=/tmp/config
  script:
    - helm upgrade --install symfony-app $CHART_DIR --set image.tag=$CI_COMMIT_SHORT_SHA
  only:
    - main
