apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.image.tag }}-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.applicationPort }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ .Chart.Name }}-{{ .Values.image.tag }}
